package lt.vu.alma6475.lab1.mybatis.model;

public class SubjectStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT_STUDENT.SUBJECTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    private Integer subjectsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT_STUDENT.STUDENTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    private Integer studentsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT_STUDENT.SUBJECTS_ID
     *
     * @return the value of PUBLIC.SUBJECT_STUDENT.SUBJECTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    public Integer getSubjectsId() {
        return subjectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT_STUDENT.SUBJECTS_ID
     *
     * @param subjectsId the value for PUBLIC.SUBJECT_STUDENT.SUBJECTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    public void setSubjectsId(Integer subjectsId) {
        this.subjectsId = subjectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT_STUDENT.STUDENTS_ID
     *
     * @return the value of PUBLIC.SUBJECT_STUDENT.STUDENTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    public Integer getStudentsId() {
        return studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT_STUDENT.STUDENTS_ID
     *
     * @param studentsId the value for PUBLIC.SUBJECT_STUDENT.STUDENTS_ID
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    public void setStudentsId(Integer studentsId) {
        this.studentsId = studentsId;
    }
}