package lt.vu.alma6475.lab1.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.TUTOR_ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    private Integer tutorId;



    // Added manually
    @Getter @Setter
    private Tutor tutor;
    @Getter @Setter
    private List<Student> students;





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @return the value of PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @param name the value for PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.TUTOR_ID
     *
     * @return the value of PUBLIC.SUBJECT.TUTOR_ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public Integer getTutorId() {
        return tutorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.TUTOR_ID
     *
     * @param tutorId the value for PUBLIC.SUBJECT.TUTOR_ID
     *
     * @mbg.generated Fri Apr 29 11:35:03 EEST 2022
     */
    public void setTutorId(Integer tutorId) {
        this.tutorId = tutorId;
    }
}