package lt.vu.alma6475.lab1.mybatis.dao;

import lt.vu.alma6475.lab1.mybatis.model.SubjectStudent;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SubjectStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT_STUDENT
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    int insert(SubjectStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT_STUDENT
     *
     * @mbg.generated Sat Apr 30 20:34:14 EEST 2022
     */
    List<SubjectStudent> selectAll();
}